language: c
cache: 
  directories:
    - build/gyp
    - build/wildo.mp4
before_script: 
  - git clone https://chromium.googlesource.com/external/gyp build/gyp --depth 3; fi
  - python gyp_ms.py -f make
  - if [ ! -f build/wildo.mp4 ]; then wget https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_30mb.mp4 -O build/wildo.mp4; fi
script: 
  - make && ./out/Default/ms_test `pwd`
after_success:
  - pip install --user cpp-coveralls
  - coveralls --exclude src/mongoose.c --exclude test --exclude build --gcov-options '\-lp'
notifications:
  email: false
  slack: wujianguo:rA9mRfVh33AimobNV3c4LdlX