language: c
before_script: 
  - git clone https://chromium.googlesource.com/external/gyp build/gyp
  - python gyp_ms.py -f make
  - pip install --user cpp-coveralls
  - wget https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_30mb.mp4 -O build/wildo.mp4
script: 
  - make & ./out `pwd`
after_success:
  - coveralls --exclude src/mongoose.c --exclude test --gcov-options '\-lp'
notifications:
  email: false
  slack: wujianguo:rA9mRfVh33AimobNV3c4LdlX